### PR TITLE
Update to work with the new API

### PR DESCRIPTION
**Pull request by BradleyShaw**

### CODE REVIEW

**Comment by MicroDroid** [comment]
Just a *suggestion*, I think `cb.snippets('new')` should rather just be `cb.snippets.new()`? I mean imagine user input passed to that function; this means someone could pass 'new' to get latest snippets, not what the programmer has intended

**Comment by Xenthys** [comment]
It would seem more logical to me if we had cb.snippets.new() and cb.snippets.get(id) yep, other than that the updated version is working so it's more a question of aesthetics.

**Comment by BradleyShaw** [comment]
How does d23dc21 look?

**Comment by MicroDroid** [comment]
It looks pretty good, thanks for your efforts :ok_hand:

**Pull request merged**
